---
title: "lista 6"
format: pdf
editor: visual
---

```{r}
library(DBI)
library(RSQLite)
con <- dbConnect(SQLite(), "me315 (5).sqlite")
```
```{sql connection=con, eval=TRUE}
SELECT *  FROM PRESERVE

```

```{sql connection=con, eval=TRUE}
SELECT *  FROM EMPLOYEE

```


1) Para cada estado mencionado na tabela PRESERVE, exiba o valor de ACRES da menor área de preservação natural localizada nesse estado.

```{sql connection=con, eval=TRUE}
SELECT STATE, MIN(ACRES), MAX(ACRES) FROM PRESERVE
GROUP BY STATE

```


2) Não considere nenhuma área de preservação natural que tenha mais de 10.000 acres. Para cada estado mencionado na tabela PRESERVE, exiba o valor de ACRES da maior área de preservação natural localizada nesse estado.

```{sql connection=con, eval=TRUE}
SELECT STATE, MIN(ACRES), MAX(ACRES)  FROM PRESERVE
WHERE ACRES < 10000
GROUP BY STATE

```


3) Na Tabela resultante anterior, ordene os resultados pelos valores máximos, em ordem decrescente.

```{sql connection=con, eval=TRUE}
SELECT STATE, MIN(ACRES), MAX(ACRES)  FROM PRESERVE
WHERE ACRES < 10000
GROUP BY STATE
ORDER BY MAX(ACRES) DESC
```


4) Exiba o tamanho, em acres, da maior área de preservação natural de cada estado, desde que esse valor seja inferior a 25.000 acres.

```{sql connection=con, eval=TRUE}
SELECT STATE, MAX(ACRES)  FROM PRESERVE
WHERE ACRES < 25000
GROUP BY STATE

```


5) Para cada estado mencionado na tabela PRESERVE, exiba o número de acres da menor área de preservação do estado, desde que esse número seja inferior a 100 acres.

```{sql connection=con, eval=TRUE}
SELECT STATE, MIN(ACRES) FROM PRESERVE
WHERE ACRES > 100
GROUP BY STATE
```

6) Considere apenas as áreas de preservação natural com mais de 1.000 acres. Para cada estado, exiba o nome e o tamanho (em acres) da maior área de preservação natural desse estado, desde que esse valor seja inferior a 25.000 acres.

```{sql connection=con, eval=TRUE}
SELECT STATE, PNAME, MAX(ACRES)  FROM PRESERVE
WHERE ACRES BETWEEN 1000 AND 25000
GROUP BY STATE

```


7) Exiba o estado e o tamanho total, em acres, das áreas de preservação localizadas nesse estado, desde que o tamanho total seja maior ou igual a 10.000 acres e menor ou igual a 50.000 acres.

```{sql connection=con, eval=TRUE}
SELECT STATE, SUM(ACRES) AS TOTAL FROM PRESERVE
GROUP BY STATE
HAVING TOTAL BETWEEN 10000 AND 50000
```

8) Determine a quantidade média de acres das áreas de preservação para cada estado e, em seguida, exiba a maior dessas médias.

```{sql connection=con, eval=TRUE}
SELECT STATE, AVG(ACRES) AS MEDIA FROM PRESERVE
GROUP BY STATE
ORDER BY MEDIA DESC
LIMIT 1
```


Os seguintes exercícios utilizam a tabela EMPLOYEE


9) Para todos os valores de DNO dos departamentos encontrados na tabela EMPLOYEE, exiba o valor de DNO, seguido pelo salário médio daquele departamento.

```{sql connection=con, eval=TRUE}
SELECT DNO, AVG(SALARY) FROM EMPLOYEE
GROUP BY DNO
```

10) Para todos os valores de DNO dos departamentos encontrados na tabela EMPLOYEE, exiba o valor de DNO, seguido pela soma, pelo máximo e pelo mínimo dos salários daquele departamento.

```{sql connection=con, eval=TRUE}
SELECT DNO, SUM(SALARY), MAX(SALARY), MIN(SALARY) FROM EMPLOYEE
GROUP BY DNO
```

11) Considere todos os departamentos, exceto o Departamento 40. Para esses departamentos, exiba o valor de DNO, seguido pelo número de funcionários que trabalham em cada departamento.

```{sql connection=con, eval=TRUE}
SELECT DNO, COUNT(ENAME) FROM EMPLOYEE
WHERE DNO <> 40
GROUP BY DNO
```

12) Para cada departamento, determine o número total de funcionários que trabalham naquele departamento. Suponha que a coluna SALARY contenha dados confidenciais e que alguém possa deduzir essas informações confidenciais examinando o total dos salários de cada departamento. Portanto, decida exibir apenas os departamentos nos quais o número de funcionários seja superior a dois.

```{sql connection=con, eval=TRUE}
SELECT DNO, COUNT(ENAME) AS FUNCIONARIOS FROM EMPLOYEE
GROUP BY DNO
HAVING FUNCIONARIOS > 2
```


13) Escreva uma solução que possa ser utilizada para reproduzir a seguinte tabela.


```{sql connection=con, eval=TRUE}
SELECT STATE, SUM(ACRES) AS TOTAL FROM PRESERVE
GROUP BY STATE
UNION ALL
SELECT 'TOTAL', SUM(ACRES) FROM PRESERVE
```
